/******************************************************************************
 * Copyright 2014-2018 Specialized Solutions LLC
 *
 * Title to the Materials (contents of this file) remain with Specialized
 * Solutions LLC.  The Materials are copyrighted and are protected by United
 * States copyright laws.  Copyright notices cannot be removed from the
 * Materials.
 *
 * See the file titled "Specialized Solutions LLC License Agreement.txt"
 * that has been distributed with this file for further licensing details.
 *
 * @brief QCM Native Functions
 *
 *****************************************************************************/
 
#pragma amxlimit 131068 /* 128 kiB available for code */
#pragma amxram 65536 /* 64 kiB available for data + stack */

#include <core>
#include <console>
#include <float>
#include <string>
#include <qcm_bdg>
#include <assert>

